// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKuJyKp5pYzonD_pZJuTtnOn8-kxyuUL4',
    appId: '1:638102056069:web:7e48fa0602c0c6f3544dec',
    messagingSenderId: '638102056069',
    projectId: 'clinicapp-32a06',
    authDomain: 'clinicapp-32a06.firebaseapp.com',
    storageBucket: 'clinicapp-32a06.appspot.com',
    measurementId: 'G-JFMQRJNPMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8zVYyNSRJ_tPBJOjVtMBrQ5cCv9PA9Fs',
    appId: '1:638102056069:android:7e2fd064925c6d9c544dec',
    messagingSenderId: '638102056069',
    projectId: 'clinicapp-32a06',
    storageBucket: 'clinicapp-32a06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDS1W0eJ0d7IxM7yQn4cEUXHwqc2gLq5s',
    appId: '1:638102056069:ios:53475720aff6df35544dec',
    messagingSenderId: '638102056069',
    projectId: 'clinicapp-32a06',
    storageBucket: 'clinicapp-32a06.appspot.com',
    androidClientId: '638102056069-458e7bktsph3ncfqu9mldinhcjci22hf.apps.googleusercontent.com',
    iosClientId: '638102056069-mkf5d57408adjbfj7676u28li4bdag8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.myDentist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDS1W0eJ0d7IxM7yQn4cEUXHwqc2gLq5s',
    appId: '1:638102056069:ios:53475720aff6df35544dec',
    messagingSenderId: '638102056069',
    projectId: 'clinicapp-32a06',
    storageBucket: 'clinicapp-32a06.appspot.com',
    androidClientId: '638102056069-458e7bktsph3ncfqu9mldinhcjci22hf.apps.googleusercontent.com',
    iosClientId: '638102056069-mkf5d57408adjbfj7676u28li4bdag8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.myDentist',
  );
}
