// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbiKRjQkLnfBAIagJyE04phrC0zEF4Uo8',
    appId: '1:774974768492:web:933986448da6de3712df49',
    messagingSenderId: '774974768492',
    projectId: 'my-dentist-ea5d0',
    authDomain: 'my-dentist-ea5d0.firebaseapp.com',
    databaseURL: 'https://my-dentist-ea5d0-default-rtdb.firebaseio.com',
    storageBucket: 'my-dentist-ea5d0.appspot.com',
    measurementId: 'G-JYVGFYPPPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeoh13NFGCNe22HTkxFZ6TlRxOVcJ8dgY',
    appId: '1:774974768492:android:274aa16badc6bc9b12df49',
    messagingSenderId: '774974768492',
    projectId: 'my-dentist-ea5d0',
    databaseURL: 'https://my-dentist-ea5d0-default-rtdb.firebaseio.com',
    storageBucket: 'my-dentist-ea5d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAccgrzLtbgn9VKgA5RhnNjzfKPSZpMr5s',
    appId: '1:774974768492:ios:8699d409a6caaab612df49',
    messagingSenderId: '774974768492',
    projectId: 'my-dentist-ea5d0',
    databaseURL: 'https://my-dentist-ea5d0-default-rtdb.firebaseio.com',
    storageBucket: 'my-dentist-ea5d0.appspot.com',
    androidClientId: '774974768492-hd7pqsivgf3fetv996q452o4b4rgknbf.apps.googleusercontent.com',
    iosClientId: '774974768492-t2fqd56clqkk680c0arme3c5hu2mt2h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.myDentist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAccgrzLtbgn9VKgA5RhnNjzfKPSZpMr5s',
    appId: '1:774974768492:ios:8699d409a6caaab612df49',
    messagingSenderId: '774974768492',
    projectId: 'my-dentist-ea5d0',
    databaseURL: 'https://my-dentist-ea5d0-default-rtdb.firebaseio.com',
    storageBucket: 'my-dentist-ea5d0.appspot.com',
    androidClientId: '774974768492-hd7pqsivgf3fetv996q452o4b4rgknbf.apps.googleusercontent.com',
    iosClientId: '774974768492-t2fqd56clqkk680c0arme3c5hu2mt2h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.myDentist',
  );
}
